### ISSUE TITLE
I am having difficulty compiling 

### ISSUE THREAD

**Issue by happytm** [jeanlemotan/esp32-cam-fpv#10]
I have to admit I never used ESP-IDF before so I am having difficulty compiling your great project. I always use Arduino IDE for my small projects.

Can you please publish compiled binary which I can upload to ESP32 or guide me to use it with Arduino ?

Thanks.

**Comment by jeanlemotan** [comment]
Hi,

Sorry for the late reply. You cannot run it with Arduino as it needs the idf to be configures differently than Arduino has it configured.

Using the idf is actually pretty easy, although the docs make it look overly complicated. Just follow the steps from the documentation and you'll make it.
