### ISSUE TITLE
can it work with openHD?

### ISSUE THREAD

**Issue by lida2003** [jeanlemotan/esp32-cam-fpv#14]
can it work with open HD?

Since there is no discussion, and I didn't find way to email.  Hope issues will get any luck response. :)

**Comment by jeanlemotan** [comment]
I don't think so. I don't have any experience with open HD, and this project uses its own protocol. Depending on the format/protocol open HD needs, it could be adapted, but I have no idea about what kind of work this could require

**Comment by lida2003** [comment]
OK, maybe I have to try my RPI 3B+, and Fix the  esp-idf 4.3 + latest code(56ee43e) constantly reboot #16
