### ISSUE TITLE
Is it possible to run the gs program on laptop?

### ISSUE THREAD

**Issue by lida2003** [jeanlemotan/esp32-cam-fpv#18]
Hope the gs program can run on laptop, which is quite useful i think.

**Comment by jeanlemotan** [comment]
With some modifications, yes. Basically, everything that is Raspberry PI specific (GL, pigpio, etc)
You'd still need the same Wifi adapters if your laptop wifi doesn't support monitor mode in just the right way.

**Comment by lida2003** [comment]
Hmmm... I got the info. thanks.

PS: [wifi tcpdump can get RF packets](https://blog.csdn.net/lida2003/article/details/128739746).
