### ISSUE TITLE
What is the limiting factor in the current system?

### ISSUE THREAD

**Issue by jtomes123** [jeanlemotan/esp32-cam-fpv#3]
Hi, what is currently the limiting factor of the whole system? Is it the camera or the esp32 itself, would offloading image processing and acquisition to another board allow lower latency at higher resolutions?

**Comment by diegovazquez** [comment]
For what i know, the limiting factor is the hardware. Sensor and bandwidth.
 
More info: https://github.com/espressif/esp32-camera/issues/15

**Comment by jeanlemotan** [comment]
Indeed, the limiting factors are the sensor (it limits the max FPS achievable and the quality is not that great), sensor->esp32 i2s bandwidth (limits the max FPS and compression, limits the number of GPIO left for other things) and esp32 wifi bandwidth (this is a tradeoff between range, bandwidth and redundancy: you can usually choose one or two of these 3 variables, but you do have full freedom to choose what you want here).
