### ISSUE TITLE
PIXFORMAT_GREYSCALE uncompressed streaming

### ISSUE THREAD

**Issue by thet0ast3r** [jeanlemotan/esp32-cam-fpv#6]
Hi, currently, this only works when using jpeg compressed streaming. Would support for high fps (30-90)fps be possible with grayscale output and a low res like 96x96?

**Comment by jeanlemotan** [comment]
Hi, most probably that would work.
The camera supports some lower resolution - not sure if as low as 96x96 - but that could be achieved by cropping the incoming data from the camera.
As for sending the data as jpeg or uncompressed - not sure why it's important to you. The jpeg is way more efficient and you can crank up the quality quite a lot. It's not just the fact that it's less data to send, it's also that there's less data to receive from the sensor - which is a limiting factor for the max FPS achievable. 

Another thing - I just remember - the camera component was indeed hacked quite a lot to improve the latency by sending the data as it arrives from the sensor. But I only changed the jpeg code, not the uncompressed one. You'd have to change that as well if you want to play with the uncompressed stream.
